export const DOCUMENT_RENDER_GENERIC_PREVIEW_MAX_CHARS_PER_LINE = 88;
export const DOCUMENT_RENDER_A4_SHORT_EDGE_MM = 210;
export const DOCUMENT_RENDER_A4_LONG_EDGE_MM = 297;
export const DOCUMENT_RENDER_PAGE_FIT_SAFETY_PX = 14;
export const DOCUMENT_RENDER_PAGE_FILL_LINE_SLACK_PX = 56;
export const DOCUMENT_RENDER_FOOTER_PAGE_FILL_SLACK_PX = 42;
export const DOCUMENT_RENDER_TABLE_SPLIT_SAFETY_PX = 10;

export function getDocumentRenderPreviewMaxCharsPerLine(isLandscape: boolean): number {
  return isLandscape
    ? Math.round(
        DOCUMENT_RENDER_GENERIC_PREVIEW_MAX_CHARS_PER_LINE *
          (DOCUMENT_RENDER_A4_LONG_EDGE_MM / DOCUMENT_RENDER_A4_SHORT_EDGE_MM)
      )
    : DOCUMENT_RENDER_GENERIC_PREVIEW_MAX_CHARS_PER_LINE;
}
