import {
  Alignment,
  Autoformat,
  BlockQuote,
  Bold,
  ClassicEditor,
  CodeBlock,
  EditorConfig,
  Essentials,
  FontBackgroundColor,
  FontColor,
  FontFamily,
  FontSize,
  GeneralHtmlSupport,
  Heading,
  Highlight,
  HorizontalLine,
  Indent,
  IndentBlock,
  Italic,
  Link,
  List,
  Paragraph,
  PasteFromOffice,
  RemoveFormat,
  SourceEditing,
  Strikethrough,
  Subscript,
  Superscript,
  Table,
  TableCaption,
  TableCellProperties,
  TableColumnResize,
  TableProperties,
  TableToolbar,
  Underline,
} from 'ckeditor5';
import { stripEditorTableChromeFromHtml } from './word-editor-table.util';

export const WORD_EDITOR_CKEDITOR = ClassicEditor;

function resolveCkeditorLicenseKey(): string {
  const globalKey = (globalThis as { __CKEDITOR_LICENSE_KEY__?: unknown }).__CKEDITOR_LICENSE_KEY__;
  return typeof globalKey === 'string' && globalKey.trim() ? globalKey.trim() : 'GPL';
}

export const WORD_EDITOR_CKEDITOR_CONFIG: EditorConfig = {
  licenseKey: resolveCkeditorLicenseKey(),
  plugins: [
    Essentials,
    Paragraph,
    Heading,
    Bold,
    Italic,
    Underline,
    Strikethrough,
    Subscript,
    Superscript,
    BlockQuote,
    CodeBlock,
    HorizontalLine,
    Autoformat,
    List,
    Indent,
    IndentBlock,
    Alignment,
    Link,
    FontFamily,
    FontSize,
    FontColor,
    FontBackgroundColor,
    Highlight,
    RemoveFormat,
    PasteFromOffice,
    SourceEditing,
    GeneralHtmlSupport,
    Table,
    TableToolbar,
    TableCaption,
    TableColumnResize,
    TableProperties,
    TableCellProperties,
  ],
  toolbar: {
    items: [
      'undo',
      'redo',
      '|',
      'heading',
      '|',
      'fontSize',
      'fontFamily',
      'fontColor',
      'fontBackgroundColor',
      'highlight',
      '|',
      'bold',
      'italic',
      'underline',
      'strikethrough',
      'subscript',
      'superscript',
      '|',
      'alignment',
      '|',
      'bulletedList',
      'numberedList',
      'outdent',
      'indent',
      '|',
      'insertTable',
      'blockQuote',
      'codeBlock',
      'horizontalLine',
      'link',
      '|',
      'removeFormat',
      'sourceEditing',
    ],
    shouldNotGroupWhenFull: true,
  },
  heading: {
    options: [
      { model: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph' },
      { model: 'heading1', view: 'h1', title: 'Heading 1', class: 'ck-heading_heading1' },
      { model: 'heading2', view: 'h2', title: 'Heading 2', class: 'ck-heading_heading2' },
      { model: 'heading3', view: 'h3', title: 'Heading 3', class: 'ck-heading_heading3' },
      { model: 'heading4', view: 'h4', title: 'Heading 4', class: 'ck-heading_heading4' },
    ],
  },
  fontSize: {
    options: [8, 9, 10, 11, 12, 14, 16, 18, 20, 24, 28, 32, 36, 48],
    supportAllValues: true,
  },
  fontFamily: {
    options: [
      'default',
      'Arial, Helvetica, sans-serif',
      'Calibri, Arial, sans-serif',
      '"Times New Roman", Times, serif',
      'Georgia, serif',
      'Tahoma, Geneva, sans-serif',
      'Verdana, Geneva, sans-serif',
      '"Courier New", Courier, monospace',
    ],
    supportAllValues: true,
  },
  table: {
    contentToolbar: [
      'tableColumn',
      'tableRow',
      'mergeTableCells',
      'splitTableCellVertically',
      'splitTableCellHorizontally',
      'toggleTableCaption',
      'tableProperties',
      'tableCellProperties',
    ],
    tableToolbar: ['insertTable'],
  },
  htmlSupport: {
    allow: [
      {
        name: /.*/,
        attributes: true,
        classes: true,
        styles: true,
      },
    ],
  },
};

export function normalizeWordEditorValueForCkeditor(value: unknown): string {
  return stripEditorTableChromeFromHtml(String(value || ''));
}
