//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.29 at 03:08:17 AM PKT 
//


package com.bezkoder.spring.login.sa.bll.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;


/**
 * <p>Java class for Zeinv complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Zeinv"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Ebeln" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="Ebelp" type="{urn:sap-com:document:sap:rfc:functions}numeric5"/&gt;
 *         &lt;element name="Aedat" type="{urn:sap-com:document:sap:rfc:functions}date10"/&gt;
 *         &lt;element name="Kdate" type="{urn:sap-com:document:sap:rfc:functions}date10"/&gt;
 *         &lt;element name="Srvpos" type="{urn:sap-com:document:sap:rfc:functions}char18"/&gt;
 *         &lt;element name="Service" type="{urn:sap-com:document:sap:rfc:functions}char30"/&gt;
 *         &lt;element name="Txz01" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="Meins" type="{urn:sap-com:document:sap:rfc:functions}unit3"/&gt;
 *         &lt;element name="Menge" type="{urn:sap-com:document:sap:rfc:functions}quantum13.3"/&gt;
 *         &lt;element name="Netwr" type="{urn:sap-com:document:sap:rfc:functions}curr15.2"/&gt;
 *         &lt;element name="TaxCode" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="Lifnr" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="Vendor" type="{urn:sap-com:document:sap:rfc:functions}char30"/&gt;
 *         &lt;element name="Telf1" type="{urn:sap-com:document:sap:rfc:functions}char16"/&gt;
 *         &lt;element name="Telf2" type="{urn:sap-com:document:sap:rfc:functions}char16"/&gt;
 *         &lt;element name="Stras" type="{urn:sap-com:document:sap:rfc:functions}char35"/&gt;
 *         &lt;element name="Ort01" type="{urn:sap-com:document:sap:rfc:functions}char35"/&gt;
 *         &lt;element name="Street" type="{urn:sap-com:document:sap:rfc:functions}char60"/&gt;
 *         &lt;element name="Roomnumber" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="NameCo" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="Email" type="{urn:sap-com:document:sap:rfc:functions}char50"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Zeinv", propOrder = {
    "ebeln",
    "ebelp",
    "aedat",
    "kdate",
    "srvpos",
    "service",
    "txz01",
    "meins",
    "menge",
    "netwr",
    "taxCode",
    "lifnr",
    "vendor",
    "telf1",
    "telf2",
    "stras",
    "ort01",
    "street",
    "roomnumber",
    "nameCo",
    "email"
})
public class Zeinv {

    @XmlElement(name = "Ebeln", required = true)
    protected String ebeln;
    @XmlElement(name = "Ebelp", required = true)
    protected String ebelp;
    @XmlElement(name = "Aedat", required = true)
    protected String aedat;
    @XmlElement(name = "Kdate", required = true)
    protected String kdate;
    @XmlElement(name = "Srvpos", required = true)
    protected String srvpos;
    @XmlElement(name = "Service", required = true)
    protected String service;
    @XmlElement(name = "Txz01", required = true)
    protected String txz01;
    @XmlElement(name = "Meins", required = true)
    protected String meins;
    @XmlElement(name = "Menge", required = true)
    protected BigDecimal menge;
    @XmlElement(name = "Netwr", required = true)
    protected BigDecimal netwr;
    @XmlElement(name = "TaxCode", required = true)
    protected String taxCode;
    @XmlElement(name = "Lifnr", required = true)
    protected String lifnr;
    @XmlElement(name = "Vendor", required = true)
    protected String vendor;
    @XmlElement(name = "Telf1", required = true)
    protected String telf1;
    @XmlElement(name = "Telf2", required = true)
    protected String telf2;
    @XmlElement(name = "Stras", required = true)
    protected String stras;
    @XmlElement(name = "Ort01", required = true)
    protected String ort01;
    @XmlElement(name = "Street", required = true)
    protected String street;
    @XmlElement(name = "Roomnumber", required = true)
    protected String roomnumber;
    @XmlElement(name = "NameCo", required = true)
    protected String nameCo;
    @XmlElement(name = "Email", required = true)
    protected String email;

    /**
     * Gets the value of the ebeln property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEbeln() {
        return ebeln;
    }

    /**
     * Sets the value of the ebeln property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEbeln(String value) {
        this.ebeln = value;
    }

    /**
     * Gets the value of the ebelp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEbelp() {
        return ebelp;
    }

    /**
     * Sets the value of the ebelp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEbelp(String value) {
        this.ebelp = value;
    }

    /**
     * Gets the value of the aedat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAedat() {
        return aedat;
    }

    /**
     * Sets the value of the aedat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAedat(String value) {
        this.aedat = value;
    }

    /**
     * Gets the value of the kdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKdate() {
        return kdate;
    }

    /**
     * Sets the value of the kdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKdate(String value) {
        this.kdate = value;
    }

    /**
     * Gets the value of the srvpos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrvpos() {
        return srvpos;
    }

    /**
     * Sets the value of the srvpos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrvpos(String value) {
        this.srvpos = value;
    }

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setService(String value) {
        this.service = value;
    }

    /**
     * Gets the value of the txz01 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxz01() {
        return txz01;
    }

    /**
     * Sets the value of the txz01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxz01(String value) {
        this.txz01 = value;
    }

    /**
     * Gets the value of the meins property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeins() {
        return meins;
    }

    /**
     * Sets the value of the meins property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeins(String value) {
        this.meins = value;
    }

    /**
     * Gets the value of the menge property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMenge() {
        return menge;
    }

    /**
     * Sets the value of the menge property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMenge(BigDecimal value) {
        this.menge = value;
    }

    /**
     * Gets the value of the netwr property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNetwr() {
        return netwr;
    }

    /**
     * Sets the value of the netwr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNetwr(BigDecimal value) {
        this.netwr = value;
    }

    /**
     * Gets the value of the taxCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxCode() {
        return taxCode;
    }

    /**
     * Sets the value of the taxCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxCode(String value) {
        this.taxCode = value;
    }

    /**
     * Gets the value of the lifnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLifnr() {
        return lifnr;
    }

    /**
     * Sets the value of the lifnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLifnr(String value) {
        this.lifnr = value;
    }

    /**
     * Gets the value of the vendor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendor() {
        return vendor;
    }

    /**
     * Sets the value of the vendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendor(String value) {
        this.vendor = value;
    }

    /**
     * Gets the value of the telf1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelf1() {
        return telf1;
    }

    /**
     * Sets the value of the telf1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelf1(String value) {
        this.telf1 = value;
    }

    /**
     * Gets the value of the telf2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelf2() {
        return telf2;
    }

    /**
     * Sets the value of the telf2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelf2(String value) {
        this.telf2 = value;
    }

    /**
     * Gets the value of the stras property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStras() {
        return stras;
    }

    /**
     * Sets the value of the stras property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStras(String value) {
        this.stras = value;
    }

    /**
     * Gets the value of the ort01 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrt01() {
        return ort01;
    }

    /**
     * Sets the value of the ort01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrt01(String value) {
        this.ort01 = value;
    }

    /**
     * Gets the value of the street property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreet() {
        return street;
    }

    /**
     * Sets the value of the street property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreet(String value) {
        this.street = value;
    }

    /**
     * Gets the value of the roomnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoomnumber() {
        return roomnumber;
    }

    /**
     * Sets the value of the roomnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoomnumber(String value) {
        this.roomnumber = value;
    }

    /**
     * Gets the value of the nameCo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameCo() {
        return nameCo;
    }

    /**
     * Sets the value of the nameCo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameCo(String value) {
        this.nameCo = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

}
