//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.29 at 03:08:17 AM PKT 
//


package com.bezkoder.spring.login.sa.bll.dto;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Itab" type="{urn:sap-com:document:sap:soap:functions:mc-style}ZtEinv"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "itab"
})
@XmlRootElement(name = "ZkfEInvoiceWebServiceResponse")
public class ZkfEInvoiceWebServiceResponse {

    @XmlElement(name = "Itab", required = true)
    protected ZtEinv itab;

    /**
     * Gets the value of the itab property.
     * 
     * @return
     *     possible object is
     *     {@link ZtEinv }
     *     
     */
    public ZtEinv getItab() {
        return itab;
    }

    /**
     * Sets the value of the itab property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZtEinv }
     *     
     */
    public void setItab(ZtEinv value) {
        this.itab = value;
    }

}
