//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.02.06 at 05:45:15 PM PKT 
//


package com.bezkoder.spring.login.ses;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.howtodoinjava.schemas.school package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.howtodoinjava.schemas.school
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZKFEINVOICESESWEBSERVICE }
     * 
     */
    public ZKFEINVOICESESWEBSERVICE createZKFEINVOICESESWEBSERVICE() {
        return new ZKFEINVOICESESWEBSERVICE();
    }

    /**
     * Create an instance of {@link ZKFEINVOICESESWEBSERVICEResponse }
     * 
     */
    public ZKFEINVOICESESWEBSERVICEResponse createZKFEINVOICESESWEBSERVICEResponse() {
        return new ZKFEINVOICESESWEBSERVICEResponse();
    }

    /**
     * Create an instance of {@link ZBAPIRET2 }
     * 
     */
    public ZBAPIRET2 createZBAPIRET2() {
        return new ZBAPIRET2();
    }

    /**
     * Create an instance of {@link BAPIRET2 }
     * 
     */
    public BAPIRET2 createBAPIRET2() {
        return new BAPIRET2();
    }

}
