//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.02.06 at 05:45:15 PM PKT 
//


package com.bezkoder.spring.login.ses;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BAPI_RETURN" type="{urn:sap-com:document:sap:rfc:functions}ZBAPIRET2"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bapireturn"
})
@XmlRootElement(name = "ZKF_E_INVOICE_SES_WEB_SERVICEResponse")
public class ZKFEINVOICESESWEBSERVICEResponse {

    @XmlElement(name = "BAPI_RETURN", required = true)
    protected ZBAPIRET2 bapireturn;

    /**
     * Gets the value of the bapireturn property.
     * 
     * @return
     *     possible object is
     *     {@link ZBAPIRET2 }
     *     
     */
    public ZBAPIRET2 getBAPIRETURN() {
        return bapireturn;
    }

    /**
     * Sets the value of the bapireturn property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZBAPIRET2 }
     *     
     */
    public void setBAPIRETURN(ZBAPIRET2 value) {
        this.bapireturn = value;
    }

}
