export const cities = {
    "data": [
        {
            "serCityId": 70,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00070",
            "txtCityName": "GUJJAR KHAN",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 72,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00072",
            "txtCityName": "KHUSHAAB",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 75,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00075",
            "txtCityName": "WAH CANTT",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 77,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00077",
            "txtCityName": "DG KHAN",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 1,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00001",
            "txtCityName": "KARACHI",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 2,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00002",
            "txtCityName": "LAHORE",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 3,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00003",
            "txtCityName": "GUJRANWALA",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 4,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00004",
            "txtCityName": "FAISALABAD",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 5,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00005",
            "txtCityName": "WAZIRABAD",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 6,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00006",
            "txtCityName": "HASSANABDAL",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 7,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00007",
            "txtCityName": "MULTAN",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 8,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00008",
            "txtCityName": "SUKKUR",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 9,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00009",
            "txtCityName": "WUHAN",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 10,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00010",
            "txtCityName": "Sawat",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 11,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00011",
            "txtCityName": "North Wazristan Agency",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 12,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00012",
            "txtCityName": "Kohat",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 13,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00013",
            "txtCityName": "ABBOTTABAD",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 14,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00014",
            "txtCityName": "HARIPUR",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 15,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00015",
            "txtCityName": "SWAT",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 16,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00016",
            "txtCityName": "HYDERABAD",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 17,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00017",
            "txtCityName": "LAHORE",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 18,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00018",
            "txtCityName": "SHIEKHUPURA",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 19,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00019",
            "txtCityName": "ISLAMABAD",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 20,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00020",
            "txtCityName": "FAISALABAD",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 21,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00021",
            "txtCityName": "LAKKI MARWAT",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 22,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00022",
            "txtCityName": "MIRPUR KHAS",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 23,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00023",
            "txtCityName": "F.R.KOHAT",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 24,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00024",
            "txtCityName": "RAWALPINDI",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 26,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00026",
            "txtCityName": "NORTH WAZIRISTAN AGENCY",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 27,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00027",
            "txtCityName": "SWAT",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 28,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00028",
            "txtCityName": "SAHIWAL",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 29,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00029",
            "txtCityName": "JHANG",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 30,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00030",
            "txtCityName": "KHAEWAL",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 31,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00031",
            "txtCityName": "MOHMAND AGENCY",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 32,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00032",
            "txtCityName": "LOWER DIR",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 33,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00033",
            "txtCityName": "ABBOTTABAD",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 34,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00034",
            "txtCityName": "CHAKWAL",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 35,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00035",
            "txtCityName": "F.R.KOHAT",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 36,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00036",
            "txtCityName": "SAWABI",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 37,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00037",
            "txtCityName": "UPPER DIR",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 38,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00038",
            "txtCityName": "MIRPUR",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 39,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00039",
            "txtCityName": "CHAKWAL",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 40,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00040",
            "txtCityName": "LAHORE",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 41,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00041",
            "txtCityName": "HARIPUR",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 42,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00042",
            "txtCityName": "HYDERABAD",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 43,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00043",
            "txtCityName": "MANSEHRA",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 44,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00044",
            "txtCityName": "MALAKUND",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 45,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00045",
            "txtCityName": "BAJOR AGENCY",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 46,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00046",
            "txtCityName": "BATAGRAM",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 47,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00047",
            "txtCityName": "Buner",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 48,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00048",
            "txtCityName": "D.G. KHAN",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 49,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00049",
            "txtCityName": "SWABI",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 50,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00050",
            "txtCityName": "PASHEEN",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 51,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00051",
            "txtCityName": "SADIQABAD",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 52,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00052",
            "txtCityName": "PESHAWAR",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 54,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00054",
            "txtCityName": "SARGODHA",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 55,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00055",
            "txtCityName": "ATTOCK",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 56,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00056",
            "txtCityName": "KASOOR",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 57,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00057",
            "txtCityName": "SIALKOT",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 58,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00058",
            "txtCityName": "DAHARAKI",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 59,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00059",
            "txtCityName": "GUJRAT",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 60,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00060",
            "txtCityName": "MURIDKE",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        },
        {
            "serCityId": 53,
            "blIsDeleted": false,
            "blnStatus": true,
            "txtCityCode": "00053",
            "txtCityName": "QUETTA",
            "numFreight": null,
            "numFreight14": null,
            "numFreight20": null,
            "numFreight40": null,
            "cfgTblCountry": {
                "serCountryId": 1,
                "blIsDeleted": false,
                "blnIsnational": null,
                "blnStatus": true,
                "dteCreateddate": null,
                "dteModifieddate": 1658312034161,
                "serCreatedUserId": null,
                "serModifiedUserId": 2,
                "serParentCountryId": null,
                "txtMachineIp": null,
                "txtName": "Pakistan",
                "cfgTblCities": null,
                "cfgTblCustomers": null
            },
            "cfgTblCustomers": null,
            "cfgTblSuppliers": null,
            "slsTblSaleOrders": null
        }
    ]
}

export const cities2 = {
    "data": [
        {
            "serCityId": 1,
            "blIsDeleted": true,
            "blnStatus": true,
            "txtCityCode": "000675",
            "txtCityName": "Lahore",
            "numFreight": 0,
            "numFreight14": 0,
            "numFreight20": 0,
            "numFreight40": 0,
            "cfgTblCountry": {
                "serCountryId": 0,
                "blIsDeleted": true,
                "blnIsnational": true,
                "blnStatus": true,
                "dteCreateddate": "2024-09-13T21:36:45.845Z",
                "dteModifieddate": "2024-09-13T21:36:45.845Z",
                "serCreatedUserId": 0,
                "serModifiedUserId": 0,
                "serParentCountryId": 0,
                "txtMachineIp": "string",
                "txtName": "Pakistan",
                "cfgTblCities": [
                    "string"
                ],
                "cfgTblCustomers": [
                    {
                        "serCustomerId": 0,
                        "blIsDeleted": true,
                        "blnIsFiler": true,
                        "blnStatus": true,
                        "dteCreateddate": "2024-09-13T21:36:45.846Z",
                        "dteModifieddate": "2024-09-13T21:36:45.846Z",
                        "numDiscount": 0,
                        "numExciseDuty": 0,
                        "numSalesTax": 0,
                        "numFED": 0,
                        "numFurtherTax": 0,
                        "serCreatedUserId": 0,
                        "serGroupId": 0,
                        "serModifiedUserId": 0,
                        "txtBillingAddress": "string",
                        "txtBusinessName": "string",
                        "txtCnicNo": "string",
                        "txtCustomerCode": "string",
                        "txtInvoiceName": "string",
                        "txtCustomerName": "string",
                        "txtDisplayAddress": "string",
                        "txtEmailAddress": "string",
                        "txtGstNameOnInvoice": "string",
                        "txtGstNumber": "string",
                        "txtIsFiler": "string",
                        "txtMachineIp": "string",
                        "txtMobileNo": "string",
                        "txtNtnNo": "string",
                        "txtSTR": "string",
                        "txtFTN": "string",
                        "txtProvince": "string",
                        "txtFName": "string",
                        "dteExpiryDate": "2024-09-13T21:36:45.846Z",
                        "dteDOB": "2024-09-13T21:36:45.846Z",
                        "txtExpiryDate": "string",
                        "txtPhoneNo": "string",
                        "txtPhoneNo2": "string",
                        "blnCommercial": true,
                        "blnPassanger": true,
                        "blnIsGst": true,
                        "txtShippingAddress": "string",
                        "cfgTblCity": "string",
                        "cfgTblCountry": "string",
                        "cfgTblCustomerCategory": {
                            "serCustomerCategoryId": 0,
                            "blIsDeleted": true,
                            "blnStatus": true,
                            "dteCreateddate": "2024-09-13T21:36:45.846Z",
                            "dteModifieddate": "2024-09-13T21:36:45.846Z",
                            "numSalecTax": 0,
                            "serCreatedUserId": 0,
                            "serGroupId": 0,
                            "serModifiedUserId": 0,
                            "serParentCategoryId": 0,
                            "txtCustomerCategoryCode": "string",
                            "txtCustomerCategoryName": "string",
                            "txtDescription": "string",
                            "txtMachineIp": "string",
                            "cfgTblCustomers": [
                                "string"
                            ]
                        },
                        "txtXMSent": "string",
                        "txtReturnMsg": "string",
                        "txtXMReceive": "string",
                        "blIsDealer": true,
                        "cfgTblCustomer": "string",
                        "txtSapNo": "string",
                        "txtUserName": "string",
                        "blIsGroup": true,
                        "blIsAccountExist": true,
                        "blIsLabsa": true,
                        "cfgTblGroupCustomer": "string",
                        "blnIsExport": true,
                        "txtDivision": "string",
                        "txtDesignation": "string",
                        "txtHOD": "string",
                        "txtHODMobile": "string",
                        "txtHODLandLine": "string",
                        "txtHODEmailAddress": "string",
                        "txtErrorMsgFromSap": "string",
                        "blIsPOSTEDToSAP": true
                    }
                ]
            },
            "cfgTblCustomers": [
                {
                    "serCustomerId": 0,
                    "blIsDeleted": true,
                    "blnIsFiler": true,
                    "blnStatus": true,
                    "dteCreateddate": "2024-09-13T21:36:45.846Z",
                    "dteModifieddate": "2024-09-13T21:36:45.846Z",
                    "numDiscount": 0,
                    "numExciseDuty": 0,
                    "numSalesTax": 0,
                    "numFED": 0,
                    "numFurtherTax": 0,
                    "serCreatedUserId": 0,
                    "serGroupId": 0,
                    "serModifiedUserId": 0,
                    "txtBillingAddress": "string",
                    "txtBusinessName": "string",
                    "txtCnicNo": "string",
                    "txtCustomerCode": "string",
                    "txtInvoiceName": "string",
                    "txtCustomerName": "string",
                    "txtDisplayAddress": "string",
                    "txtEmailAddress": "string",
                    "txtGstNameOnInvoice": "string",
                    "txtGstNumber": "string",
                    "txtIsFiler": "string",
                    "txtMachineIp": "string",
                    "txtMobileNo": "string",
                    "txtNtnNo": "string",
                    "txtSTR": "string",
                    "txtFTN": "string",
                    "txtProvince": "string",
                    "txtFName": "string",
                    "dteExpiryDate": "2024-09-13T21:36:45.846Z",
                    "dteDOB": "2024-09-13T21:36:45.846Z",
                    "txtExpiryDate": "string",
                    "txtPhoneNo": "string",
                    "txtPhoneNo2": "string",
                    "blnCommercial": true,
                    "blnPassanger": true,
                    "blnIsGst": true,
                    "txtShippingAddress": "string",
                    "cfgTblCity": "string",
                    "cfgTblCountry": "string",
                    "cfgTblCustomerCategory": {
                        "serCustomerCategoryId": 0,
                        "blIsDeleted": true,
                        "blnStatus": true,
                        "dteCreateddate": "2024-09-13T21:36:45.846Z",
                        "dteModifieddate": "2024-09-13T21:36:45.846Z",
                        "numSalecTax": 0,
                        "serCreatedUserId": 0,
                        "serGroupId": 0,
                        "serModifiedUserId": 0,
                        "serParentCategoryId": 0,
                        "txtCustomerCategoryCode": "string",
                        "txtCustomerCategoryName": "string",
                        "txtDescription": "string",
                        "txtMachineIp": "string",
                        "cfgTblCustomers": [
                            "string"
                        ]
                    },
                    "txtXMSent": "string",
                    "txtReturnMsg": "string",
                    "txtXMReceive": "string",
                    "blIsDealer": true,
                    "cfgTblCustomer": "string",
                    "txtSapNo": "string",
                    "txtUserName": "string",
                    "blIsGroup": true,
                    "blIsAccountExist": true,
                    "blIsLabsa": true,
                    "cfgTblGroupCustomer": "string",
                    "blnIsExport": true,
                    "txtDivision": "string",
                    "txtDesignation": "string",
                    "txtHOD": "string",
                    "txtHODMobile": "string",
                    "txtHODLandLine": "string",
                    "txtHODEmailAddress": "string",
                    "txtErrorMsgFromSap": "string",
                    "blIsPOSTEDToSAP": true
                }
            ]
        }
    ],
    "message": "string",
    "success": true,
    "timestamp": "2024-09-13T21:36:45.846Z",
    "status": "100 CONTINUE"
}

export const newCity = {
    "serCityId": 0,
    "blIsDeleted": true,
    "blnStatus": true,
    "txtCityCode": "string",
    "txtCityName": "string",
    "numFreight": 0,
    "numFreight14": 0,
    "numFreight20": 0,
    "numFreight40": 0,
    "cfgTblCountry": {
        "serCountryId": 0,
        "blIsDeleted": true,
        "blnIsnational": true,
        "blnStatus": true,
        "dteCreateddate": "2024-09-13T21:47:24.256Z",
        "dteModifieddate": "2024-09-13T21:47:24.256Z",
        "serCreatedUserId": 0,
        "serModifiedUserId": 0,
        "serParentCountryId": 0,
        "txtMachineIp": "string",
        "txtName": "string",
        "cfgTblCities": [
            "string"
        ],
        "cfgTblCustomers": [
            {
                "serCustomerId": 0,
                "blIsDeleted": true,
                "blnIsFiler": true,
                "blnStatus": true,
                "dteCreateddate": "2024-09-13T21:47:24.256Z",
                "dteModifieddate": "2024-09-13T21:47:24.256Z",
                "numDiscount": 0,
                "numExciseDuty": 0,
                "numSalesTax": 0,
                "numFED": 0,
                "numFurtherTax": 0,
                "serCreatedUserId": 0,
                "serGroupId": 0,
                "serModifiedUserId": 0,
                "txtBillingAddress": "string",
                "txtBusinessName": "string",
                "txtCnicNo": "string",
                "txtCustomerCode": "string",
                "txtInvoiceName": "string",
                "txtCustomerName": "string",
                "txtDisplayAddress": "string",
                "txtEmailAddress": "string",
                "txtGstNameOnInvoice": "string",
                "txtGstNumber": "string",
                "txtIsFiler": "string",
                "txtMachineIp": "string",
                "txtMobileNo": "string",
                "txtNtnNo": "string",
                "txtSTR": "string",
                "txtFTN": "string",
                "txtProvince": "string",
                "txtFName": "string",
                "dteExpiryDate": "2024-09-13T21:47:24.256Z",
                "dteDOB": "2024-09-13T21:47:24.256Z",
                "txtExpiryDate": "string",
                "txtPhoneNo": "string",
                "txtPhoneNo2": "string",
                "blnCommercial": true,
                "blnPassanger": true,
                "blnIsGst": true,
                "txtShippingAddress": "string",
                "cfgTblCity": "string",
                "cfgTblCountry": "string",
                "cfgTblCustomerCategory": {
                    "serCustomerCategoryId": 0,
                    "blIsDeleted": true,
                    "blnStatus": true,
                    "dteCreateddate": "2024-09-13T21:47:24.256Z",
                    "dteModifieddate": "2024-09-13T21:47:24.256Z",
                    "numSalecTax": 0,
                    "serCreatedUserId": 0,
                    "serGroupId": 0,
                    "serModifiedUserId": 0,
                    "serParentCategoryId": 0,
                    "txtCustomerCategoryCode": "string",
                    "txtCustomerCategoryName": "string",
                    "txtDescription": "string",
                    "txtMachineIp": "string",
                    "cfgTblCustomers": [
                        "string"
                    ]
                },
                "txtXMSent": "string",
                "txtReturnMsg": "string",
                "txtXMReceive": "string",
                "blIsDealer": true,
                "cfgTblCustomer": "string",
                "txtSapNo": "string",
                "txtUserName": "string",
                "blIsGroup": true,
                "blIsAccountExist": true,
                "blIsLabsa": true,
                "cfgTblGroupCustomer": "string",
                "blnIsExport": true,
                "txtDivision": "string",
                "txtDesignation": "string",
                "txtHOD": "string",
                "txtHODMobile": "string",
                "txtHODLandLine": "string",
                "txtHODEmailAddress": "string",
                "txtErrorMsgFromSap": "string",
                "blIsPOSTEDToSAP": true
            }
        ]
    },
    "cfgTblCustomers": [
        {
            "serCustomerId": 0,
            "blIsDeleted": true,
            "blnIsFiler": true,
            "blnStatus": true,
            "dteCreateddate": "2024-09-13T21:47:24.256Z",
            "dteModifieddate": "2024-09-13T21:47:24.256Z",
            "numDiscount": 0,
            "numExciseDuty": 0,
            "numSalesTax": 0,
            "numFED": 0,
            "numFurtherTax": 0,
            "serCreatedUserId": 0,
            "serGroupId": 0,
            "serModifiedUserId": 0,
            "txtBillingAddress": "string",
            "txtBusinessName": "string",
            "txtCnicNo": "string",
            "txtCustomerCode": "string",
            "txtInvoiceName": "string",
            "txtCustomerName": "string",
            "txtDisplayAddress": "string",
            "txtEmailAddress": "string",
            "txtGstNameOnInvoice": "string",
            "txtGstNumber": "string",
            "txtIsFiler": "string",
            "txtMachineIp": "string",
            "txtMobileNo": "string",
            "txtNtnNo": "string",
            "txtSTR": "string",
            "txtFTN": "string",
            "txtProvince": "string",
            "txtFName": "string",
            "dteExpiryDate": "2024-09-13T21:47:24.256Z",
            "dteDOB": "2024-09-13T21:47:24.256Z",
            "txtExpiryDate": "string",
            "txtPhoneNo": "string",
            "txtPhoneNo2": "string",
            "blnCommercial": true,
            "blnPassanger": true,
            "blnIsGst": true,
            "txtShippingAddress": "string",
            "cfgTblCity": "string",
            "cfgTblCountry": "string",
            "cfgTblCustomerCategory": {
                "serCustomerCategoryId": 0,
                "blIsDeleted": true,
                "blnStatus": true,
                "dteCreateddate": "2024-09-13T21:47:24.256Z",
                "dteModifieddate": "2024-09-13T21:47:24.256Z",
                "numSalecTax": 0,
                "serCreatedUserId": 0,
                "serGroupId": 0,
                "serModifiedUserId": 0,
                "serParentCategoryId": 0,
                "txtCustomerCategoryCode": "string",
                "txtCustomerCategoryName": "string",
                "txtDescription": "string",
                "txtMachineIp": "string",
                "cfgTblCustomers": [
                    "string"
                ]
            },
            "txtXMSent": "string",
            "txtReturnMsg": "string",
            "txtXMReceive": "string",
            "blIsDealer": true,
            "cfgTblCustomer": "string",
            "txtSapNo": "string",
            "txtUserName": "string",
            "blIsGroup": true,
            "blIsAccountExist": true,
            "blIsLabsa": true,
            "cfgTblGroupCustomer": "string",
            "blnIsExport": true,
            "txtDivision": "string",
            "txtDesignation": "string",
            "txtHOD": "string",
            "txtHODMobile": "string",
            "txtHODLandLine": "string",
            "txtHODEmailAddress": "string",
            "txtErrorMsgFromSap": "string",
            "blIsPOSTEDToSAP": true
        }
    ]
}