//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.30 at 12:57:23 PM PKT 
//


package com.bezkoder.spring.login.workflow;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.zabetan.behpardakht.ipg.schemas.sap1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.zabetan.behpardakht.ipg.schemas.sap1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZkfInvoiceWorkflowRemarks }
     * 
     */
    public ZkfInvoiceWorkflowRemarks createZkfInvoiceWorkflowRemarks() {
        return new ZkfInvoiceWorkflowRemarks();
    }

    /**
     * Create an instance of {@link Ziwfrt }
     * 
     */
    public Ziwfrt createZiwfrt() {
        return new Ziwfrt();
    }

    /**
     * Create an instance of {@link ZkfInvoiceWorkflowRemarksResponse }
     * 
     */
    public ZkfInvoiceWorkflowRemarksResponse createZkfInvoiceWorkflowRemarksResponse() {
        return new ZkfInvoiceWorkflowRemarksResponse();
    }

    /**
     * Create an instance of {@link Ziwfrot }
     * 
     */
    public Ziwfrot createZiwfrot() {
        return new Ziwfrot();
    }

    /**
     * Create an instance of {@link Ziwfr }
     * 
     */
    public Ziwfr createZiwfr() {
        return new Ziwfr();
    }

    /**
     * Create an instance of {@link Ziwfro }
     * 
     */
    public Ziwfro createZiwfro() {
        return new Ziwfro();
    }

}
