//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.30 at 12:57:23 PM PKT 
//


package com.bezkoder.spring.login.workflow;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Ziwfro complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ziwfro"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Belnr" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="Stext" type="{urn:sap-com:document:sap:rfc:functions}char132"/&gt;
 *         &lt;element name="WiAagent" type="{urn:sap-com:document:sap:rfc:functions}char12"/&gt;
 *         &lt;element name="WiCd" type="{urn:sap-com:document:sap:rfc:functions}date10"/&gt;
 *         &lt;element name="WiCt" type="{urn:sap-com:document:sap:rfc:functions}time"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Ziwfro", propOrder = {
    "belnr",
    "stext",
    "wiAagent",
    "wiCd",
    "wiCt"
})
public class Ziwfro {

    @XmlElement(name = "Belnr", required = true)
    protected String belnr;
    @XmlElement(name = "Stext", required = true)
    protected String stext;
    @XmlElement(name = "WiAagent", required = true)
    protected String wiAagent;
    @XmlElement(name = "WiCd", required = true)
    protected String wiCd;
    @XmlElement(name = "WiCt", required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar wiCt;

    /**
     * Gets the value of the belnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBelnr() {
        return belnr;
    }

    /**
     * Sets the value of the belnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBelnr(String value) {
        this.belnr = value;
    }

    /**
     * Gets the value of the stext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStext() {
        return stext;
    }

    /**
     * Sets the value of the stext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStext(String value) {
        this.stext = value;
    }

    /**
     * Gets the value of the wiAagent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWiAagent() {
        return wiAagent;
    }

    /**
     * Sets the value of the wiAagent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWiAagent(String value) {
        this.wiAagent = value;
    }

    /**
     * Gets the value of the wiCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWiCd() {
        return wiCd;
    }

    /**
     * Sets the value of the wiCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWiCd(String value) {
        this.wiCd = value;
    }

    /**
     * Gets the value of the wiCt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getWiCt() {
        return wiCt;
    }

    /**
     * Sets the value of the wiCt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setWiCt(XMLGregorianCalendar value) {
        this.wiCt = value;
    }

}
