//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.30 at 12:57:23 PM PKT 
//


package com.bezkoder.spring.login.workflow;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ItOut" type="{urn:sap-com:document:sap:soap:functions:mc-style}Ziwfrot"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "itOut"
})
@XmlRootElement(name = "ZkfInvoiceWorkflowRemarksResponse")
public class ZkfInvoiceWorkflowRemarksResponse {

    @XmlElement(name = "ItOut", required = true)
    protected Ziwfrot itOut;

    /**
     * Gets the value of the itOut property.
     * 
     * @return
     *     possible object is
     *     {@link Ziwfrot }
     *     
     */
    public Ziwfrot getItOut() {
        return itOut;
    }

    /**
     * Sets the value of the itOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ziwfrot }
     *     
     */
    public void setItOut(Ziwfrot value) {
        this.itOut = value;
    }

}
