package com.bezkoder.spring.login.autogenerated.sap;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.util.Date;

@XmlRootElement(name = "Item")
@XmlType(propOrder = {
        "ebeln", "ebelp", "aedat", "kdate", "srvpos", "service",
        "txz01", "meins", "menge", "netwr", "taxCode", "lifnr",
        "vendor", "telf1", "telf2", "stras", "ort01", "street",
        "roomnumber", "nameCo", "email"
})
public class Item {

    private String ebeln;
    private String ebelp;
    private Date aedat;
    private String kdate;
    private String srvpos;
    private String service;
    private String txz01;
    private String meins;
    private Double menge;
    private Double netwr;
    private String taxCode;
    private String lifnr;
    private String vendor;
    private String telf1;
    private String telf2;
    private String stras;
    private String ort01;
    private String street;
    private String roomnumber;
    private String nameCo;
    private String email;

    @XmlElement(name = "EBELN")
    public String getEbeln() {
        return ebeln;
    }

    public void setEbeln(String ebeln) {
        this.ebeln = ebeln;
    }

    @XmlElement(name = "EBELP")
    public String getEbelp() {
        return ebelp;
    }

    public void setEbelp(String ebelp) {
        this.ebelp = ebelp;
    }

    @XmlElement(name = "AEDAT")
    public Date getAedat() {
        return aedat;
    }

    public void setAedat(Date aedat) {
        this.aedat = aedat;
    }

    @XmlElement(name = "KDATE")
    public String getKdate() {
        return kdate;
    }

    public void setKdate(String kdate) {
        this.kdate = kdate;
    }

    @XmlElement(name = "SRVPOS")
    public String getSrvpos() {
        return srvpos;
    }

    public void setSrvpos(String srvpos) {
        this.srvpos = srvpos;
    }

    @XmlElement(name = "SERVICE")
    public String getService() {
        return service;
    }

    public void setService(String service) {
        this.service = service;
    }

    @XmlElement(name = "TXZ01")
    public String getTxz01() {
        return txz01;
    }

    public void setTxz01(String txz01) {
        this.txz01 = txz01;
    }

    @XmlElement(name = "MEINS")
    public String getMeins() {
        return meins;
    }

    public void setMeins(String meins) {
        this.meins = meins;
    }

    @XmlElement(name = "MENGE")
    public Double getMenge() {
        return menge;
    }

    public void setMenge(Double menge) {
        this.menge = menge;
    }

    @XmlElement(name = "NETWR")
    public Double getNetwr() {
        return netwr;
    }

    public void setNetwr(Double netwr) {
        this.netwr = netwr;
    }

    @XmlElement(name = "TAX_CODE")
    public String getTaxCode() {
        return taxCode;
    }

    public void setTaxCode(String taxCode) {
        this.taxCode = taxCode;
    }

    @XmlElement(name = "LIFNR")
    public String getLifnr() {
        return lifnr;
    }

    public void setLifnr(String lifnr) {
        this.lifnr = lifnr;
    }

    @XmlElement(name = "VENDOR")
    public String getVendor() {
        return vendor;
    }

    public void setVendor(String vendor) {
        this.vendor = vendor;
    }

    @XmlElement(name = "TELF1")
    public String getTelf1() {
        return telf1;
    }

    public void setTelf1(String telf1) {
        this.telf1 = telf1;
    }

    @XmlElement(name = "TELF2")
    public String getTelf2() {
        return telf2;
    }

    public void setTelf2(String telf2) {
        this.telf2 = telf2;
    }

    @XmlElement(name = "STRAS")
    public String getStras() {
        return stras;
    }

    public void setStras(String stras) {
        this.stras = stras;
    }

    @XmlElement(name = "ORT01")
    public String getOrt01() {
        return ort01;
    }

    public void setOrt01(String ort01) {
        this.ort01 = ort01;
    }

    @XmlElement(name = "STREET")
    public String getStreet() {
        return street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    @XmlElement(name = "ROOMNUMBER")
    public String getRoomnumber() {
        return roomnumber;
    }

    public void setRoomnumber(String roomnumber) {
        this.roomnumber = roomnumber;
    }

    @XmlElement(name = "NAME_CO")
    public String getNameCo() {
        return nameCo;
    }

    public void setNameCo(String nameCo) {
        this.nameCo = nameCo;
    }

    @XmlElement(name = "EMAIL")
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
}
