package com.bezkoder.spring.login.autogenerated.sap;


import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.util.List;

// Root element
@XmlRootElement(name = "ZkfEInvoiceWebServiceResponse", namespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlType(propOrder = {"itab"})
public class ZkfEInvoiceWebServiceResponse {

    private List<Item> itab;

    @XmlElement(name = "Itab")
    public List<Item> getItab() {
        return itab;
    }

    public void setItab(List<Item> itab) {
        this.itab = itab;
    }
}

