name: VIM BACKEND CI Pipeline

on:
  push:
    branches: [ "main" ]
    paths:
      - 'VIM-BE/**'
      - '!VIM-FE/**'

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./VIM-BE

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: 'VIM-BE'
 
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Build with Maven
      run: mvn clean package
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: webapp-artifact
        path: VIM-BE/target/*.war
